### ISSUE TITLE
LiteDoge Wallet not displaying anything for Staking

### ISSUE THREAD

**Issue by melinko2003** [vashshawn/LDOGE#3]
Hi,
I've installed the wallet and fully synced all Tx's, waited a few days but the actual Staking amount isn't displaying correctly. Additionally I've set a password for my wallet and have unlocked it and the total for staking says 0. Is this a bug or is it longer than 8 hours for funds to display in the staking field? I believe it is staking as the thunderbolt says:

Staking
Your weight is 3
...

Kind Regards,
Llew

P.s I'm using 3.4.1.1 as my wallet version.

**Comment by vashshawn** [comment]
Try running the command repairwallet in the command field from help then debug then go to command. How many coins you have?

**Comment by melinko2003** [comment]
I currently have 130 coins thus far, and repairwallet returns:

{
"wallet check passed" : true
}

**Comment by IngCr3at1on** [comment]
130 coins is not nearly enough of a weight to expect a stake.

**Comment by melinko2003** [comment]
So what is the minimum threshold for staking at this time?

**Comment by t3ch9** [comment]
@melinko2003 Did you get a response to your question from anyone in the LiteDoge community?

**Comment by melinko2003** [comment]
Not yet, so no clue - I assume it's a visual bug at this point due to following the normal procedure for staking.( Ie. Unlock and check the lightning bolt which says I'm staking. ) Would be nice to know if it was a visual bug for sure or if other part of the ui is actually incorrect. Thoughts here?

**Comment by IngCr3at1on** [comment]
Sorry I've been forgetting to check github notifications lately cause we're not using it for my work anymore lol...

There is no "minimum" weight defined in the code but we could attempt to calculate a `target minimum` in a couple of ways.

---

The actual "staking weight" is calculated based on the number of coins and the age of the inputs in which said coins exist up to a max age (which unfortunately I'm not sure off the top of my head where that's defined, I was hoping chainparams.h or main.h but I don't see it)...

For arguments sake let's just say it's a max age of 7 days... 

If you multiply X (number of coins) by Y (the coin age) to get Z (the stake weight).
`X * Y = Z`

Then if you take N as the number of total inputs on the network containing coins (no clue on the number for that either, I'm not sure there's a block explorer capable of calculating that without some extra effort). You could theoretically calculate A as the median average (using N, Z and X) number of coins per input and you could probably consider that your target minimum (getting N and V (where V is the value of each input in N) is the tricky part that I don't think anyone here (or IRC for that matter) is going to be able to help with.

---

A more feasible option would be to let X be a number of previously minted blocks and Y would be the value of the coins in the staking input then just calculate a median average based off of those and you'd have a pretty good idea of a target minimum as well (the higher X is the more accurate this target will be).

---

iirc it's going to be something into the hundred thousands or even millions.

**Comment by melinko2003** [comment]
Good info to have, thanks.
