### ISSUE TITLE
compile failed due to issue with chainparams.cpp and a bad vSeeds.push.back line

### ISSUE THREAD

**Issue by liquiz** [vashshawn/LDOGE#4]
Branch - Master

The offending line is vSeeds.push_back(CDNSSeedData(""104.173.211.177", ""104.173.211.177")); which when comparing to the other vSeeds.push.back lines it would seem their are to many " in there.

Changing it to this appears to clear the problem and allow it to build
vSeeds.push_back(CDNSSeedData("104.173.211.177", "104.173.211.177"));

**Comment by vashshawn** [comment]
fixed the issue
